### ISSUE TITLE
Provide secure hardened-kernel configs

### ISSUE THREAD

**Issue by edubart** [cartesi/image-kernel#17]
## Context

Our kernel config currently doesn't enable any secure config, making its attack surface larger. We should start enabling some kernel configs to protect users from potential kernel vulnerabilities, such as:

- Init on alloc + Init on free, to mitigate user-after-free vulnerabilities.
- Use `-ftrivial-auto-var-init=zero` to always initialize uninitialized variables.

Just by enabling the above configs, already makes many CVEs found in the Linux kernel impossible to abuse.

However with every security focused config there will be some impact on general performance, we should investigate the impact with benchmarks, and maybe provide two configs in case there is too much impact.

**Note:** Have in mind that most of these kernel vulnerabilities have to be abused in userspace, usually after some privilege escalation in the dapp layer . A hardened-kernel config is just an extra layer of protection in case someone somehow manages to break the dapp protection layer. With this extra layer of protection it would be harder to "own" the machine with root privileges or cause denial of service of the machine.

## Subtasks

This should be done only after the following issues:
- https://github.com/cartesi/image-kernel/issues/16

Because some secure kernel configs are only available in recent GCC toolchains.

## Possible solutions

Investigate all kernel configs and GCC flags that make sense to enable, there is this good blog post that explore some of them [Linux Hardening Guide](https://madaidans-insecurities.github.io/guides/linux-hardening.html). Benchmark and update configs. Finally decide on the following possibilities:
- Provide just one secure hardened config, make it the default
- Provide one secure hardened config and a standard config, make the standard one the default
- Provide one secure hardened config and an "optimized" config, make the hardened one the default

**Comment by vfusco** [comment]
Was done in https://github.com/cartesi/linux/pull/11
